#include "bench/util/leaves.h"
#include "include/utreexo.h"

using namespace utreexo;

int main(int argc, char** argv)
{
    // This is a simple profiling demo.
    // The scenario that we want to profile must be written here and using
    // --enable-profiling-demo it builds to the `profiling_demo` executable.
    // The `generate_flamegraph` script profiles this code and
    // creates the flamegraph. For more details see `generate_flamegraph`.

    // ...do any setup needed...
    UndoBatch unused_undo;
    const int num_leaves = 105;

    std::vector<Leaf> leaves;
    CreateTestLeaves(leaves, num_leaves);

    /**
     * Flame graphs are generated by sampling the active stack frames at
     * regular intervals and then converting them into a flame graph.
     *
     * The endless loop is to make sure that operations of interest that
     * are relatively fast, will execute for enough time to end up on
     * stack traces and thus on the flamegraph
     */
    for (;;) {
        // ...operations to be profiled...
        RamForest full(0);                    // initialize
        full.Modify(unused_undo, leaves, {}); // add leaves
    }

    return EXIT_SUCCESS;
}